start: "2015-01-01"
end: "2099-12-31"
interval: "1d"
out_dir: "./market_data"

aliases:
  "^GSPC": "S&P500"
  "^IXIC": "Nasdaq Composite"
  "^NDX": "Nasdaq100"
  "000001.SS": "SSE Composite 上证指数"
  "399001.SZ": "SZSE Component 深证成指"
  "510300.SS": "沪深300ETF_华泰柏瑞"
  "^HSI": "Hang Seng 恒生"
  "^HSTECH": "Hang Seng TECH 恒生科技"
  "3033.HK": "恒生科技ETF_南方"
  "XAUUSD=X": "Gold Spot XAUUSD"
  "518880.SS": "华安黄金ETF_518880"

  # —— 新增：A股行业（更稳妥：用ETF作代理，抓取成功率更高）——
  "159928.SZ": "中证消费ETF_159928"
  "159938.SZ": "中证医药ETF_159938"
  "159845.SZ": "中证新能源ETF_159845"

  # —— 新增：海外市场 —— 
  "^N225": "Nikkei225 日本"
  "^NSEI": "Nifty50 印度"
  "^STOXX50E": "EuroStoxx50 欧洲"

  # —— 新增：宏观风向 —— 
  "DX-Y.NYB": "美元指数DXY"       # 若抓取失败，可换用 "DX=F"
  "^TNX": "美债10年期收益率"
  "CL=F": "WTI原油"
  "BZ=F": "Brent原油"

tickers:
  # 你已有的核心
  - "^GSPC"         # S&P 500
  - "^IXIC"         # 纳指综合
  - "000001.SS"     # 上证
  - "399001.SZ"     # 深证
  - "510300.SS"     # 沪深300 ETF 代理
  - "^HSI"          # 恒生
  - "^HSTECH"       # 恒生科技
  - "3033.HK"       # 恒科ETF
  - "XAUUSD=X"      # 现货金
  - "518880.SS"     # 华安黄金ETF

  # 新增增强与分散
  - "^NDX"          # 纳斯达克100
  - "159928.SZ"     # 中证消费 ETF
  - "159938.SZ"     # 中证医药 ETF
  - "159845.SZ"     # 中证新能源 ETF
  - "^N225"         # 日经225
  - "^NSEI"         # 印度Nifty50
  - "^STOXX50E"     # 欧元区50

  # 宏观风向
  - "DX-Y.NYB"      # 美元指数（如失败换 "DX=F"）
  - "^TNX"          # 美债10Y收益率
  - "CL=F"          # WTI 原油
  - "BZ=F"          # Brent 原油
