start: "2015-01-01"
end: "2099-12-31"
interval: "1d"
out_dir: "./market_data"

aliases:
  # ==== 核心 ====
  "^GSPC": "S&P500 标普500"
  "^IXIC": "Nasdaq Composite 纳指综合"
  "^NDX": "Nasdaq100 纳指100"
  "000001.SS": "SSE Composite 上证指数"
  "399001.SZ": "SZSE Component 深证成指"
  "510300.SS": "沪深300ETF_华泰柏瑞"
  "518880.SS": "华安黄金ETF_518880"
  "XAUUSD=X": "Gold Spot 现货黄金"

  # ==== 港股 ====
  "^HSI": "Hang Seng 恒生指数"
  "^HSTECH": "Hang Seng TECH 恒生科技"
  "3033.HK": "恒生科技ETF_南方"
  "2800.HK": "恒生指数ETF_盈富基金"
  "3067.HK": "恒生医疗ETF_华夏"
  "2822.HK": "南方A50 ETF 港股通"

  # ==== A股行业 ====
  "159928.SZ": "中证消费ETF_159928"
  "159938.SZ": "中证医药ETF_159938"
  "159845.SZ": "中证新能源ETF_159845"
  "159915.SZ": "创业板ETF_159915"
  "512880.SS": "证券公司ETF_512880"

  # ==== 海外市场 ====
  "^STOXX50E": "EuroStoxx50 欧洲斯托克50"
  "^N225": "Nikkei225 日本日经225"
  "^NSEI": "Nifty50 印度"

  # ==== 宏观风向 ====
  "DX-Y.NYB": "美元指数DXY"       # 若抓取失败，可换 "DX=F"
  "^TNX": "美债10年期收益率"
  "CL=F": "WTI原油"
  "BZ=F": "Brent原油"

tickers:
  # ==== 核心 ====
  - "^GSPC"         # 标普500
  - "^IXIC"         # 纳指综合
  - "^NDX"          # 纳指100
  - "000001.SS"     # 上证指数
  - "399001.SZ"     # 深证成指
  - "510300.SS"     # 沪深300 ETF
  - "518880.SS"     # 黄金ETF（华安）
  - "XAUUSD=X"      # 现货黄金

  # ==== 港股 ====
  - "^HSI"          # 恒生指数
  - "^HSTECH"       # 恒生科技
  - "3033.HK"       # 恒生科技ETF
  - "2800.HK"       # 恒生指数ETF
  - "3067.HK"       # 恒生医疗ETF
  - "2822.HK"       # 南方A50 ETF

  # ==== A股行业 ====
  - "159928.SZ"     # 中证消费ETF
  - "159938.SZ"     # 中证医药ETF
  - "159845.SZ"     # 中证新能源ETF
  - "159915.SZ"     # 创业板ETF
  - "512880.SS"     # 券商ETF

  # ==== 海外市场 ====
  - "^STOXX50E"     # 欧洲斯托克50
  - "^N225"         # 日经225
  - "^NSEI"         # 印度Nifty50

  # ==== 宏观风向 ====
  - "DX-Y.NYB"      # 美元指数（若失败换 DX=F）
  - "^TNX"          # 美债10年期收益率
  - "CL=F"          # WTI 原油
  - "BZ=F"          # Brent 原油
